apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: python-node-github-actions-quay-060625
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-node-github-actions-quay-060625 
  name: python-node-github-actions-quay-060625
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-node-github-actions-quay-060625
    weight: 100 
