apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python-node-github-actions-quay-060625
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-node-github-actions-quay-060625 
  name: python-node-github-actions-quay-060625
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python-node-github-actions-quay-060625 
